### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by hagolo** [simon816/PHPDeobfuscator#1]
Hello
Thank you simon816 for amazing script . we want use it but we found a missing file require 'vendor/autoload.php';

vendor/autoload.php
can you please help us to get this file please ?

**Comment by simon816** [comment]
Oh, that's from [Composer](https://getcomposer.org/), I should provide instructions on the README.

What you'll need to do is get `composer`, either from the website https://getcomposer.org/download/ or from your package manager (on linux).
Then `cd` into the repo root (where [`composer.json`](https://github.com/simon816/PHPDeobfuscator/blob/master/composer.json) is located), and run `composer install`. It will download the dependencies and generate a `vendor/autoload.php` for you.

**Comment by hagolo** [comment]
> Oh, that's from [Composer](https://getcomposer.org/), I should provide instructions on the README.
> 
> What you'll need to do is get `composer`, either from the website https://getcomposer.org/download/ or from your package manager (on linux).
> Then `cd` into the repo root (where [`composer.json`](https://github.com/simon816/PHPDeobfuscator/blob/master/composer.json) is located), and run `composer install`. It will download the dependencies and generate a `vendor/autoload.php` for you.

Thanks you
