### ISSUE TITLE
Variable restoration failure

### ISSUE THREAD

**Issue by L2ksy0d** [simon816/PHPDeobfuscator#11]
When there is a branch control statement in the middle of the code segment (for example, if, while), the variable reduction after the branch is invalid.

INPUT
```php
<?php
$a = 'b';
$b = 'm';
$i=1;

echo $a;
echo $b;
```
OUTPUT
```php
<?php    
         
$a = 'b';
$b = 'm';
$i = 1;  
echo "b";
echo "m";
```

INPUT
```php
<?php
$a = 'b';
$b = 'm';
$i=1;
while($i<=5)
{
    echo "The number is " . $i . "<br>";
    $i++;
}
echo $i;
echo $a;
echo $b;
```

OUTPUT
```php
<?php                                   
                                        
$a = 'b';                               
$b = 'm';                               
$i = 1;                                 
while ($i <= 5) {                       
    echo "The number is " . $i . "<br>";
    $i++;                               
} 
                                      
echo $i;                                
echo $a;                                
echo $b; 
```
The values of $a and $b are not restored.
Branch statements may interfere with the normal operation of Scope and Resolver.

**Comment by simon816** [comment]
Yeah this is a known limitation. When a branch is encountered, it clears the value of all variables in scope, in case the variable is mutated in the branch/loop.
See https://github.com/simon816/PHPDeobfuscator/blob/f70baa3a460b28dad1b8391979924e89c00364fe/src/Resolver.php#L79-L90
The deobfuscator does not do analysis on whether the variables are unchanged, so this is the safest option for now. It should be possible to do this but it's a slightly difficult problem to solve.

**Comment by L2ksy0d** [comment]
This takes into account the various syntax and assignments that can occur in a branching statement, and it's a really hard project 😀, I'll keep trying.

**Comment by L2ksy0d** [comment]
Another problem is that a function syntax block with variables can cause a program to exit unexpectedly：
```php
<?php

$a = 'exec';
$b = 'ls';
function writeName()
{
    echo "Kai Jim Refsnes";
}

function test($a, $b) {
    return @$a($b);
}

test($a, $b);
```
