### ISSUE TITLE
Function names are case-insensitive

### ISSUE THREAD

**Issue by L2ksy0d** [simon816/PHPDeobfuscator#12]
Function names with mixed case cannot be restored properly.
```php
<?php
    $K=sTr_RepLaCe('`','',chr('111').'`s`s`e`r`t');
```
I believe that the reduceFunctionCall function in FuncCallReducer did not convert the function name to lower case.

https://github.com/simon816/PHPDeobfuscator/blob/f70baa3a460b28dad1b8391979924e89c00364fe/src/Reducer/FuncCallReducer.php#L26-L38

Use strtolower() here to ensure that $name is lowercase.

```diff
public function reduceFunctionCall(Node\Expr\FuncCall $node)
    {
        if ($node->name instanceof Node\Name) {
-            $name = $node->name->toString();
+           $name = strtolower($node->name->toString());
        } else {
            $name = Utils::getValue($node->name);
            $nameNode = new Node\Name($name);
            // Special case for MetadataVisitor
            $nameNode->setAttribute('replaces', $node->name);
            $node->name = $nameNode;
        }
        return $this->makeFunctionCall($name, $node);
    }
```

https://github.com/L2ksy0d/PHPDeobfuscator/blob/e275b9265e8139df2208233ac4f08f588dd3c484/src/Reducer/FuncCallReducer.php#L26-L38

**Comment by simon816** [comment]
Thanks, fixed.
