### ISSUE TITLE
fclose(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by JosefSommerauer** [simon816/PHPDeobfuscator#18]
Some files throw ``fclose(): supplied resource is not a valid stream resource`` Error.

Suggested fix:
https://github.com/simon816/PHPDeobfuscator/blob/3f5f3b1914a0dabed2fe38ec53f8f2cf0d181b59/src/Reducer/FuncCallReducer/FileSystemCall.php#L133

```
     private function fclose(ResourceValue $handle)
     {
        if (is_resource($handle->getResource())) {
           fclose($handle->getResource());
        }
     }
```

**Comment by simon816** [comment]
Thanks for the bug report. I've fixed this in a slightly different way - by tracking whether a file handle has been closed and ignoring file handle functions once it's closed.
