### ISSUE TITLE
PHP Fatal error:  Uncaught LogicException:

### ISSUE THREAD

**Issue by MasterB0t** [simon816/PHPDeobfuscator#4]
PHP Fatal error:  Uncaught LogicException: Path is outside of the defined root, path: [../init.php] in /home/chris/Downloads/PHPDeobfuscator-master/vendor/league/flysystem/src/Util.php:118
Stack trace:
#0 /home/chris/Downloads/PHPDeobfuscator-master/vendor/league/flysystem/src/Util.php(92): League\Flysystem\Util::normalizeRelativePath('../init.php')
#1 /home/chris/Downloads/PHPDeobfuscator-master/vendor/league/flysystem/src/Filesystem.php(56): League\Flysystem\Util::normalizePath('../init.php')
#2 /home/chris/Downloads/PHPDeobfuscator-master/src/Reducer/EvalReducer.php(40): League\Flysystem\Filesystem->has('../init.php')
#3 /home/chris/Downloads/PHPDeobfuscator-master/src/Reducer/AbstractReducer.php(39): Reducer\EvalReducer->reduceInclude(Object(PhpParser\Node\Expr\Include_))
#4 /home/chris/Downloads/PHPDeobfuscator-master/src/ReducerVisitor.php(33): Reducer\AbstractReducer->reduce(Object(PhpParser\Node\Expr\Include_), Object(ReducerVisitor))
#5 /home/chris/Downloads/PHPDeobfuscator-master/src/ReducerVisitor.php(24): ReducerVisitor->reduceNode(Object(PhpParser\Node\Expr\Include_))
#6 /home/chris/Downloads/PHPDeobfuscator-master/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(178): ReducerVisitor->leaveNode(Object(PhpParser\Node\Expr\Include_))
#7 /home/chris/Downloads/PHPDeobfuscator-master/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#8 /home/chris/Downloads/PHPDeobfuscator-master/src/Deobfuscator.php(104): PhpParser\NodeTraverser->traverse(Array)
#9 /home/chris/Downloads/PHPDeobfuscator-master/index.php(16): Deobfuscator->deobfuscate(Array)
#10 /home/chris/Downloads/PHPDeobfuscator-master/index.php(29): deobfuscate('<?php\r\ngoto b1a...', '/home/chris//cl...', false)
#11 {main}
  thrown in /home/chris/Downloads/PHPDeobfuscator-master/vendor/league/flysystem/src/Util.php on line 118

**Comment by simon816** [comment]
I agree this shouldn't be a fatal error.

It seems to be coming from an `include` of the path `../init.php`.

**Comment by MasterB0t** [comment]
OK I found the what was wrong. the file I was trying to run with PHPDeobfuscator had a require 'init.php'; line that was causing the issue.
