### ISSUE TITLE
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by HalJordan** [simon816/PHPDeobfuscator#7]
src/Reducer/EvalReducer.php

```
src/Reducer/EvalReducer.php:        if (substr($code, 0, 2) == '?>' && $code{2} != '<') {
src/Reducer/EvalReducer.php:            $code{0} = '<';
src/Reducer/EvalReducer.php:            $code{1} = '?';
```

Those 3 lines just need to be changed.

**Comment by simon816** [comment]
For reference, this is due to curly braces for string indexes being removed in PHP 8:

https://www.php.net/manual/en/language.types.string.php
>    Note: Prior to PHP 8.0.0, strings could also be accessed using braces, as in $str{42}, for the same purpose. This curly brace syntax was deprecated as of PHP 7.4.0 and no longer supported as of PHP 8.0.0.
