### ISSUE TITLE
Problem with more than two consecutive goto labels. 

### ISSUE THREAD

**Issue by beneri** [simon816/PHPDeobfuscator#9]
When the code has more than two consecutive labels we get an error and the resulting code still has the two first labels (which should be removed I believe). 
Example: 

Input:
```
goto LabelA;
LabelA: 
LabelB: 
LabelC: 
echo 'hello';
```

Output: 
```
LabelA:
LabelB:
echo "hello";
```

Expected output: 
```
echo "hello";
```

**Comment by beneri** [comment]
The direct warning seems to be because `LabelA` is not part of
 `$this->exitBlock->entersPerName` in the `rebuild` function in  ControlFlowVisitor.php. 

But I haven't figured out yet why it, in general, only adds the two last labels to the entersPerName array.

**Comment by simon816** [comment]
This has been fixed now (detailed in the linked commit)
I also encountered several other bugs while investigating this one, which have been fixed.

Have started adding test cases too to help prevent regressions.
